apiVersion: v1
kind: ConfigMap
metadata:
  name: liceo-db-config
  labels:
    app: liceo
data:
  PGDATA: {{ .Values.db.deployment.pg_data }}
  POSTGRES_USER: {{ .Values.db.deployment.username }}
  POSTGRES_PASSWORD: {{ .Values.db.deployment.password }}
  POSTGRES_DB: {{ .Values.db.deployment.name }}