apiVersion: v1
kind: Service
metadata:
  name: liceo-db
  labels:
    app: liceo
    tier: db
spec:
  ports:
    - port: {{ .Values.db.service.port }}
      protocol: TCP
      targetPort: {{ .Values.db.service.port }}
  selector:
    app: liceo
    tier: db
  clusterIP: None