apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: liceo-web
  labels:
    app: liceo
    tier: web
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: liceo-web
              servicePort: 8080