apiVersion: v1
kind: Service
metadata:
  name: liceo-web
  labels:
    app: liceo
    tier: web
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.service.port }}
      protocol: TCP
      targetPort: {{ .Values.web.service.port }}
  selector:
    app: liceo
    tier: web